### ISSUE TITLE
Allow keyboard hotkeys to select belt-bar items when belt is toggled

### ISSUE THREAD

**Issue by Bobder** [JamCoreModding/utility-belt#12]
It would be great to have the ability to select the tools on my belt using my keyboard keys as long as I've toggled the belt on

**Comment by Jamalam360** [comment]
Makes sense, thanks.

Note to self: probably have a config option that switches between the buttons throwing you out of the belt back to the hotbar, and the buttons being usable in the belt

**Comment by Jamalam360** [comment]
Thank you, will be released soon.
