### ISSUE TITLE
utilitybelt:set_utility_belt_selected_slot_c2s can cause ArrayIndexOutOfBoundsExceptions

### ISSUE THREAD

**Issue by LunexLunertic** [JamCoreModding/utility-belt#13]
For preface I had this mod for over a month now with no issues, so this bug only happened today and might just be an exception. Nonetheless I will make a report here just in case for anyone else experiencing this.

I believe this happened when I scrolled too fast(?) when I was on the utility belt toolbar as the logs show that somehow it went out of bounds within the confines of the bar.

[latest.log](https://github.com/JamCoreModding/UtilityBelt/files/9769400/latest.log)

Ignore any other errors beforehand (and the log spam of constant open GL errors as that one is just from somewhere and can be ignored), the one related to the "Utility Belt" is the last one that took me out. I will update this to see if it happens again later today.

**Comment by Jamalam360** [comment]
That's really weird...thanks for reporting, I'll look into it when I get a chance

**Comment by Jamalam360** [comment]
Ok seems other people are experiencing this. My guess is there's some slight lag between the server/client syncing so if you change slots at a specific rate the client can send invalid indexes causing the server to crash.

**Comment by Jamalam360** [comment]
Thanks for reporting, unsure whether it is fixed (applied my best guess solution) so please reopen this if you experience it again.
