### ISSUE TITLE
Thrown weapons with loyalty dupe.

### ISSUE THREAD

**Issue by Jwellison** [JamCoreModding/utility-belt#17]
On the 19.2 medieval minecraft pack as a base, if you put a thrown weapon (Trident, Javelin, etc) with loyalty enchant in the tool belt, when you throw it, you will receive a second copy in the regular inventory when it returns.

**Comment by Jamalam360** [comment]
Oh no! I'll look into it tomorrow, thank you for reporting.

**Comment by Jamalam360** [comment]
Thanks for reporting
