### ISSUE TITLE
Tool in the first slot behaves strangely in multiplayer

### ISSUE THREAD

**Issue by Hyomoto** [JamCoreModding/utility-belt#23]
This is a bit bizarre, though I don't know if any of it is ending up in the log.  I also tried it in single player and it doesn't seem to have the same issue (though at one point the game *did* crash, but I'm not sure if that's related).  Short version, in multiplayer the first tool in the utility belt ... doesn't quite work.  The block will disappear, and then reappear and then a while later disappear again.  Tools like a hammer from "vanilla hammers" will, like above, cause the blocks to disappear and reappear and then just one block will break.  Tools like the shears still work but behave like you are just normally breaking a block, ie: smack a grass and it will drop seeds or nothing rather than the grass.  The hoe behaves like a shovel, when you right click it will create a path instead of farmland.

Tools in the *other* slots, however, seem to behave normally.  So yeah, the tool in the first slot behaves strangely in multiplayer.

![image](https://user-images.githubusercontent.com/6281477/212993619-0c81cdff-aca8-4a14-8697-d39d07898cc8.png)
![image](https://user-images.githubusercontent.com/6281477/212993647-1ccaa651-03df-47a5-b42b-f024eca4f070.png)

**Comment by Jamalam360** [comment]
This mod gets more and more confusing......

Thanks for the report. I'll try look into it soon

**Comment by HaloGamer33** [comment]
I have also encountered this problem; it kind of acts like rubber banding.

https://user-images.githubusercontent.com/106188903/226827842-261ef723-c3ff-40ed-aae8-3e3307f19152.mp4

**Comment by Jamalam360** [comment]
I can confirm this after testing. I can't remove the tool from the first tool via shift + b either.

**Comment by Jamalam360** [comment]
Durability also doesn't go down for the first slot tool

**Comment by Jamalam360** [comment]
- Try to break a block with the first slot tool
- Rubber banding as above
- Move the tool to the second slot via GUI
- Block will break
