### ISSUE TITLE
Sneak+toggle button crashes the server

### ISSUE THREAD

**Issue by variety754** [JamCoreModding/utility-belt#24]
When I sneak and press toggle button to switch from utility belt to hotbar it crashes server with message "Internal Exception: java.lang.ArrayIndexOutOfBoundsException"
![image](https://user-images.githubusercontent.com/124847943/217987482-4e8a11d2-e34d-4ba1-96b5-5b6a58201075.png)

**Comment by variety754** [comment]
Oh, forgot to say. I have version 1.19.3 of minecraft with 0.14.14 fabric loader.

**Comment by Jamalam360** [comment]
I cannot do anything about this without a log, and I'm assuming that hasn't been saved. Hopefully it will be fixed by me going and fixing other issues, feel free to reopen if you run into it again.
