### ISSUE TITLE
crashing on launch

### ISSUE THREAD

**Issue by VoldeZortS** [JamCoreModding/utility-belt#29]
I use a mod pack that includes utility belt and when it crushes ı copy the crash log and paste it on ''mclo.gs'' which says to me that utility belt is throwing an exception, when i go and look the problem it says something like this

<html>
<body>

---- Minecraft Crash Report ----
--
619 | // Surprise! Haha. Well, this is awkward.
620 |  
621 | Time: 2023-07-24 13:17:11
622 | Description: Initializing game
623 |  
624 | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'utilitybelt'!
625 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
626 | at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
627 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
628 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
629 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
630 | at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
631 | at net.minecraft.client.main.Main.main(Main.java:211)
632 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
633 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
634 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
635 | Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: utilitybelt:ut\u0131l\u0131ty_belt
636 | at net.minecraft.util.Identifier.validatePath(Identifier.java:252)
637 | at net.minecraft.util.Identifier.<init>(Identifier.java:47)
638 | at io.github.jamalam360.jamlib.registry.JamLibRegistry.getIdentifier(JamLibRegistry.java:324)
639 | at io.github.jamalam360.jamlib.registry.JamLibRegistry.register(JamLibRegistry.java:238)
640 | at io.github.jamalam360.jamlib.registry.JamLibRegistry.register(JamLibRegistry.java:192)
641 | at io.github.jamalam360.utility.belt.UtilityBeltInit.onInitialize(UtilityBeltInit.java:80)
642 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
643 | ... 7 more

</body>
</html>

what should i do? I don't know how to get to the utilitybelt location. If you guys need more information i can provide it

**Comment by Jamalam360** [comment]
It looks like a file might be corrupted. You can try redownloading utility belt/your modpack

**Comment by VoldeZortS** [comment]
> It looks like a file might be corrupted. You can try redownloading utility belt/your modpack

tired it but didn't worked

**Comment by Jamalam360** [comment]
What language do you use on your computer?

**Comment by VoldeZortS** [comment]
yes it is Turkish

**Comment by Jamalam360** [comment]
Alright, it's an unexpected issue where the lowercase of `I` in Turkish is not `i`. I will fix it now.

**Comment by Jamalam360** [comment]
Please try updating 'Jam Lib' to V0.6.1

[modrinth](https://modrinth.com/mod/jamlib/versions)

[curseforge](https://www.curseforge.com/minecraft/mc-mods/jamlib/files)

**Comment by VoldeZortS** [comment]
it worked! thank you so much

**Comment by Jamalam360** [comment]
Thanks for reporting
