### ISSUE TITLE
Belt is lost even if keepInventory is true 

### ISSUE THREAD

**Issue by Jamalam360** [JamCoreModding/utility-belt#31]
https://www.curseforge.com/minecraft/mc-mods/utility-belt#c4

**Comment by thea-apianae** [comment]
I'm still getting this issue in 1.21, not sure why

**Comment by Jamalam360** [comment]
Yes, looks like it was a regression with the port to accessories. Thanks for letting me know

**Comment by Jamalam360** [comment]
2.4.1 should fix this
