### ISSUE TITLE
Tools in utility belt not working

### ISSUE THREAD

**Issue by GamerTable** [JamCoreModding/utility-belt#36]
When quick switching to the utility belt hotbar on a server on most occasions the tool will show up client-side but "switch back" after one use to the normal hotbar. Idk its odd to explain lmao. 

https://github.com/JamCoreModding/utility-belt/assets/114619268/8a6e059a-441b-41ec-8df9-91e62cb28265

https://github.com/JamCoreModding/utility-belt/assets/114619268/716d80d5-0e31-4f6f-ad22-61213f3388c7

1.20.1 Fabric Utility Belt 1.3.6

**Comment by GamerTable** [comment]
Cool, Thanks!

**Comment by Amzd** [comment]
I have the same issue, when a tools durability changes it deselects the belt. (so with unbreaking you can get a few hits in but with unenchanted it is only one hit)

Is there a beta version available?

**Comment by Jamalam360** [comment]
For 1.20.4 a beta version should be released today. 1.20.1 and 1.20.2 will be soon after but can't guarantee they'll be released today.

Other versions are now considered out of support
