### ISSUE TITLE
Background texture off by one pixel

### ISSUE THREAD

**Issue by Abbie5** [JamCoreModding/utility-belt#38]
![2024-04-02_21 58 47](https://github.com/JamCoreModding/utility-belt/assets/43531981/a81032e1-1b61-4ea9-ae3c-ed0a89384fd7)

especially visible on the hilt of the sword

**Comment by Abbie5** [comment]
https://0x0.st/Xz6m.txt

**Comment by Jamalam360** [comment]
Oh god yeah that's really obvious now I look at it properly. Will fix tomorrow
