### ISSUE TITLE
2.0.0 for [other Minecraft version]?

### ISSUE THREAD

**Issue by Jamalam360** [JamCoreModding/utility-belt#39]
While I had originally planned to backport V2.0.0 to Minecraft 1.20.1 and 1.20.2, I unfortunately can't any more. It would effectively mean porting 3 mods[^1], which I don't have time for.

As 1.20.5 is released, Utility Belt will be updated to that. 1.20.4 will **remain in support** for as long as V2.0.0 is in beta, or for as long as there are critical bugs.

[^1]: Utility Belt, Baubly [Trinkets & Curios abstraction layer], and JamLib [which is outdated on those versions compared to 1.20.4]

**Comment by Jamalam360** [comment]
Because I was getting so many bug reports for them and I knew that they were flawed. They had the potential to just...delete your items. Or dupe your items. I wasn't going to leave that for people to download.

**Comment by Jamalam360** [comment]
On curseforge they are archived, so existing modpacks using those versions still have them, but modrinth doesn't have an archive functionality that I can see

**Comment by Boden-C** [comment]
Since you switched from Baubly to Accessories, which supports 1.20.1, can you reconsider backporting again?

If not, I'm trying to find the latest 1.20.1 download with the full understanding that it's buggy. I have a pretty flexible smp, and everyone has op, so it's fine if things get deleted or duped.

**Comment by Jamalam360** [comment]
I think 1.3.6 was the latest.

It's not due to what accessory mod I was using, it's internal Minecraft changes. There's a non-zero change that there will be a backport, but it's very unlikely.
