### ISSUE TITLE
Placing belted item in off-hand via keybind duplicates it

### ISSUE THREAD

**Issue by PossiblyNocturnal** [JamCoreModding/utility-belt#44]
Hi, been playing on my 1.20.4 world with 2.1.0 version of the mod when I noticed that the sword I had equipped on my belt duplicated into my inventory after I placed it in my off-hand using the keybind. Tried it bunch more times and each time it worked the exact same way. The dupe isn't purely visual - restarting the world didn't remove the duplicated swords. It seems like the mod doesn't catch on that the item has been removed from the belt in other ways apart from the mod's own gui and keybinds, so it keeps the item in the belt and just copies it in your off-hand.

I have some other mods installed, but the only ones interacting with the inventory(and it's gui) would be Inventory Sorter and Exordium, although I don't think a mod limiting gui's fps and a mod adding a button to sort items in the inventory can cause this.

Not sure if it's relevant, but I'm using 0.15.11 version of Fabric Loader and 0.97.0 version of Fabric API.

**Comment by Jamalam360** [comment]
Thanks for the report. You're actually not intended to be able to use the offhand key while in the belt, but the condition checking for that was incorrect. 1.20.6 update released, 1.20.4 coming shortly
