### ISSUE TITLE
[1.20.6] Item duplication when adding tools to belt

### ISSUE THREAD

**Issue by ffuentesm** [JamCoreModding/utility-belt#45]
ver:utility-belt-neoforge-2.1.1+1.20.6.jar
Neoforge: 20.6.75

When I right-click to add tools to the belt, like you do with a bundle, the tool is duplicated in the belt. 
![image](https://github.com/JamCoreModding/utility-belt/assets/44974827/d91ece66-f33a-4aa5-80d3-e647f260af3c)

And if the belt is full and I try to right-click to remove the items, it will delete two items. 
![image](https://github.com/JamCoreModding/utility-belt/assets/44974827/65b13843-e515-4e6b-910e-d7d9ffa017d7)

**Comment by Jamalam360** [comment]
Thanks for reporting. I started looking into this but decided I'll just work on it tomorrow, because I think the fix should involve some refactoring to make sure stuff like this can't happen

**Comment by Jamalam360** [comment]
Weird thing: this does not happen in creative mode

**Comment by Jamalam360** [comment]
Fixed, might not release for a while though as I want to do some intensive play testing to find any other issues
