### ISSUE TITLE
[1.20.4]  Fishing Rod glitch

### ISSUE THREAD

**Issue by perrilol** [JamCoreModding/utility-belt#47]
![2024-06-04_10 12 22](https://github.com/JamCoreModding/utility-belt/assets/171631634/8170a3cf-3752-4b37-b7ed-4db084d7c51e)
Fabric
When using fishring rood on the belt, it starts to glitch and flicker

**Comment by Jamalam360** [comment]
Hi, not sure what you mean exactly, could you provide any more details? I can't see any issue with both an unenchanted and enchanted rod. Do you have any other mods that might be messing with fishing?
