### ISSUE TITLE
Equipping Utility Belt Causes Server To Crash

### ISSUE THREAD

**Issue by momoshamiko** [JamCoreModding/utility-belt#48]
After installing on my fabric server, when you try to equip the belt it crashes the server. If you restart the server and then try to log back into it, the server crashes again.
[2024-06-29-4.log.gz](https://github.com/user-attachments/files/16041184/2024-06-29-4.log.gz)
[2024-06-29-3.log.gz](https://github.com/user-attachments/files/16041185/2024-06-29-3.log.gz)

**Comment by momoshamiko** [comment]
[crash-2024-06-29_15.42.47-server.txt](https://github.com/user-attachments/files/16041190/crash-2024-06-29_15.42.47-server.txt)
[crash-2024-06-29_15.44.27-server.txt](https://github.com/user-attachments/files/16041191/crash-2024-06-29_15.44.27-server.txt)

**Comment by Jamalam360** [comment]
Thanks for reporting, should be fixed in next release
