### ISSUE TITLE
dupe bug report 

### ISSUE THREAD

**Issue by kads-e** [JamCoreModding/utility-belt#57]
https://www.youtube.com/watch?v=HH1Pwvs17Uo
got this send and was told report it because laziness is a thing, would assume is multiplayer only, but would need testing 
version: utilitybelt-1.3.3+1.19.2
happened on MI: foundation, but they said it would also happen with only this mod/the problem was this mod?

**Comment by Jamalam360** [comment]
Sorry, 1.20.1 are no longer support
