### ISSUE TITLE
1.21 (NeoForge) - Utility belt refuses to allow lanterns or torches in its inventory

### ISSUE THREAD

**Issue by ToxinZangoose** [JamCoreModding/utility-belt#58]
Minecraft Version 1.21.1
NeoForge Version 21.1.73
Utility Belt Version 2.5.0 - 1.21.1

Hello,

I've been enjoying using this mod but recently I found an issue with it.

I have tried pressing the keybind to swap hands to the utility belt, both the toggle and the hold buttons, and I've tried opening the GUI for the belt itself by keybind.

Each time, the belt rejects my attempts to place a torch or lantern in it to light up my mining trips.

If this is a known issue with NeoForge or if I need to swap to Forge instead, let me know please.

Thank you for your time, I look forward to seeing the next update. :smile:

**Comment by Jamalam360** [comment]
Hi, lanterns and torches aren't allowed in the belt by default. Usually only tools are allowed in it. If you are comfortable with datapacks you could add to the `utility_belt:allowed_in_utility_belt` item tag.

P.S. I recently added compatibility with LambDynamicLights on Fabric. If that is installed, you can put torches and lanterns in the belt. If there is a dynamic light mod you use on Neoforge let me know and I can try add compatibility with it.

**Comment by ToxinZangoose** [comment]
I see, interesting.
I was using Sodium Dynamic Lights, but wondered if RyonamicLights would be supported since it's an unofficial port of LamDynamicLights.
