### ISSUE TITLE
Crash - Fabric 1.21.1

### ISSUE THREAD

**Issue by Gamemassa** [JamCoreModding/utility-belt#59]
MC - 1.21.1
Fabric Loader - 0.16.9
Fabric API - 0.110.0
JamLib - 1.2.2
Utility Belt - 2.5.0

Hi, Utility Belt is causing a crash in my custom modpack. Not sure why. Crash report and latest.log are below:

Crash Report:
https://mclo.gs/LQ7JYVP

Latest.log:
https://mclo.gs/DLYcCSQ

**Comment by Jamalam360** [comment]
Fixed in latest version, thanks for reporting
